services:
  btaudio:
    build: ./
    privileged: true
    network_mode: host
    # Required to keep persistent pairing state
    #volumes:
    #  - /var/containers/btaudio:/var/lib/bluetooth:rw
    # Set the bluetooth MAC address on startup
    environment:
      BT_MAC_ADDRESS: "DC:A6:32:B5:20:16"
