version: "3.9"

services:
  btaudio:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    # Required to keep persistent pairing state
    #volumes:
    #  - /var/containers/btaudio:/var/lib/bluetooth:rw
